# Generated by Django 5.2 on 2025-04-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dish/'),
        ),
        migrations.AddField(
            model_name='dishtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dish_type/'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
